server:
  port: 0

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 5s
    stream:
      bindings:
        output:
          binder: kafka
          destination: cloudEX
      kafka:
        binder:
          replicationFactor: 1